#!/bin/sh

# gamepad_id='8C:41:F2:07:02:3F'
gamepad_id='0C:35:26:23:E7:DE'

if  ! (systemctl -q is-active bluetooth) 
then
	systemctl enable bluetooth
	systemctl start bluetooth
fi

bluetoothctl power on
timeout 5 bluetoothctl scan on
timeout 5 bluetoothctl cancel-pairing $gamepad_id
timeout 5 bluetoothctl disconnect $gamepad_id
bluetoothctl pair $gamepad_id
bluetoothctl connect $gamepad_id
