#!/bin/sh

# Install neovim
yay neovim
bash nvim-configs/requirements

DIR=~/.config/nvim
[ -d "$DIR" ] && rm -rf "$DIR"

mkdir $DIR

rsync -av --exclude=".*" nvim-configs/* $DIR

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install rootless docker
curl -fsSL https://get.docker.com/rootless | sh
sudo pacman -S docker-compose
