#!/bin/sh

# Install neovim
bash vim-configs/install-nvim-config

# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install rootless docker
curl -fsSL https://get.docker.com/rootless | sh
sudo pacman -S docker-compose
