#!/bin/sh

bash install-dependencies
bash install-suckless-programs
bash coder-setup
bash install-fonts
bash install-steam
bash personal-setups
bash xserver-configs-install
bash install-virtual-machine
sudo pacman -R $(pacman -Qdtq)

