#!/bin/sh

echo "-- Full Install --"

bash install-scripts/install-utilities
bash install-scripts/install-fonts

echo "-- Get Repositories --"
git submodule update --init --recursive --remote
echo "-- Get Repositories End"

bash install-scripts/install-suckless-programs &
bash setup-scripts/xserver-configs-install &
wait

echo "-- Autoremove --"
sudo pacman -R $(sudo pacman -Qdtq)
echo "-- Autoremove End --"

echo "-- Full Install End --"
