#!/bin/sh

bash vim-configs/install-vimb-config

cd wyebadblock

make clean
WEBKITVER=4.1 make
sudo WEBKITVER=4.1 make install

cd ..

wget -nv -O ~/.config/wyebadblock/easylist.txt https://easylist.to/easylist/easylist.txt
sudo ln -s /usr/lib/wyebrowser/4.1/adblock.so /usr/lib/vimb
