#!/bin/sh

gamepad_id='8C:41:F2:07:02:3F'

if  ! (systemctl -q is-active bluetooth) 
then
	systemctl enable bluetooth
	systemctl start bluetooth
fi

bluetoothctl power on
timeout 5 bluetoothctl scan on
# bluetoothctl cancel-pairing $gamepad_id
bluetoothctl disconnect $gamepad_id
bluetoothctl pair $gamepad_id
bluetoothctl connect $gamepad_id
