#!/bin/sh

wallpaper_dir=~/.config/wall.png

[ -f "$1" ] && cp "$1" $wallpaper_dir && notify-send -i $wallpaper_dir "Wallpaper Changed"

[ -d "$1" ] && mv "find "$1"/*.{jpg,jpeg,png} -type f | shuf -n 1" $wallpaper_dir && notify-send -i $wallpaper_dir "Random Wallpaper Chosen"

# If pywal is installed, use it.
type wal >/dev/null 2>&1 && { wal -c
    wal -s -i $wallpaper_dir -o ~/.config/wal/postrun
    xsetroot -name "fsignal:xrdb"
    killall dwmblocks
    setsid dwmblocks >/dev/null & } >/dev/null 2>&1

xwallpaper --zoom $wallpaper_dir