#!/bin/sh

source ../location-vars

# Applying patches
git apply patches/*

# Installing suckless programs
modules_to_install='dwm dmenu st slstatus surf'

for module in $main_repo_path/$modules_to_install; do
    echo $module
    cd $module
    sudo rm config.h
    sudo make clean install
    sudo rm config.h
    sudo make clean
    git checkout -- .
    cd $install_scripts_path
done
