#!/bin/sh

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

cd $MAIN_REPO_PATH/mutt-configs

bash install-mutt
bash config-mutt

cd $INSTALL_REPO_PATH
