#!/bin/sh

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

echo "-- Installing Dependencies --"

xargs -rxa $INSTALL_SCRIPT_PATH/dependencies -- sudo pacman -Sy --noconfirm --

echo "-- Installing Dependencies End --"

echo "-- Install Utilities --"

xargs -rxa $SCRIPTPATH/utilities -- sudo pacman -Sy --noconfirm --

echo "-- Install Utilities End --"
