#!/bin/sh

echo "-- Installing Fonts --"

read -p "you want to install the fonts? (type y)" -n 1 -r
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
   exit
fi

DIR=~/.local/share/fonts
TMP=/tmp/fonts
FONTS='JetBrainsMono Noto'

[[ -d "$DIR" ]] && rm -rf $DIR
mkdir $DIR 

mkdir $TMP
cd $TMP

for font in $FONTS; do
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/$font.zip
    unzip $font.zip -d ~/.local/share/fonts
done

sudo fc-cache -fv
cd ../..
rm -rf $TMP

echo "-- Installing Fonts End --"
