#!/bin/sh

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

# Applying patches
git apply $MAIN_REPO_PATH/patches/*

# Installing suckless programs
modules_to_install='dwm dmenu st slstatus surf'

for module in $MAIN_REPO_PATH/$modules_to_install; do
    echo $module
    cd $module
    sudo rm config.h
    sudo make clean install
    sudo rm config.h
    sudo make clean
    git checkout -- .
    cd $INSTALL_SCRIPTS_PATH
done
