#!/bin/sh

echo "-- Install Code Editor --"

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

EDITOR_OPTIONS='vim neovim'

select editor in $EDITOR_OPTIONS; do 
   case $editor in 
	   vim)
		   bash $MAIN_REPO_PATH/vim-configs/install-vim-config
		   break ;;
	   neovim)
		   bash $MAIN_REPO_PATH/vim-configs/install-nvim-config
		   break ;;
   esac
done

echo "-- Install Code Editor End --"

echo "-- Install Rust --"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
echo "-- Install Rust End --"

echo "-- Install Haskell --"
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
echo "-- Install Haskell End --"

echo "-- Install Rootless Docker --"
curl -fsSL https://get.docker.com/rootless | sh
sudo pacman -S docker-compose
echo "-- Install Rootless Docker End --"
