#!/bin/sh

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

# Installing dependencies
xargs -rxa $INSTALL_SCRIPT_PATH/dependencies -- sudo pacman -Sy --

# Install yay
cd $MAIN_REPO_PATH/yay
makepkg -si
cd $INSTALL_SCRIPT_PATH
