#!/bin/sh

echo "-- Install Steam --"

sudo sed -i '/^\#\[multilib\]/ {s/^\#\[multilib\]$/\[multilib\]/;N; s/\#Include/Include/g}' /etc/pacman.conf

sudo pacman -Suy --noconfirm && sudo pacman -Sy steam --noconfirm

echo "-- Install Steam End --"
