#!/bin/sh

# Install editor

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

EDITOR_OPTIONS='vim neovim'

select editor in $EDITOR_OPTIONS; do 
   case $editor in 
	   vim)
		   bash $MAIN_REPO_PATH/vim-configs/install-vim-config
		   break ;;
	   neovim)
		   bash $MAIN_REPO_PATH/vim-configs/install-nvim-config
		   break ;;
   esac
done


# Install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# Install haskell
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

# Install rootless docker
curl -fsSL https://get.docker.com/rootless | sh
sudo pacman -S docker-compose
