#!/bin/sh

echo "-- Browser Config --"

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

bash $MAIN_REPO_PATH/vim-configs/install-vimb-config

echo "-- Browser Config End --"
