#!/bin/sh

echo "-- Browser Config --"

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source $SCRIPTPATH/location-vars

bash $MAIN_REPO_PATH/vim-configs/install-vimb-config

(cd $MAIN_REPO_PATH/wyebadblock
make clean
WEBKITVER=4.1 make
sudo WEBKITVER=4.1 make install)

wget -nv -O ~/.config/wyebadblock/easylist.txt https://easylist.to/easylist/easylist.txt
sudo ln -s /usr/lib/wyebrowser/4.1/adblock.so /usr/lib/vimb

echo "-- Browser Config End --"
