#!/bin/sh

echo "-- Configure Personal Scripts --"

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PERSONALSCRIPTPATH=$SCRIPTPATH/custom-scripts

for file in $PERSONALSCRIPTPATH/*
do
  sudo chmod +x $file
done

sudo cp $PERSONALSCRIPTPATH/* /usr/local/bin/
echo "All the personal scripts were added/updated"

echo "-- Configure Sersonal Scripts End --"
