#!/bin/sh

SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
XSERVERPATH=$SCRIPTPATH/xserver-configs

cp $XSERVERPATH/xinitrc-default ~/.xinitrc
cp $XSERVERPATH/xprofile-default ~/.xprofile
echo "xinitrc and xprofile were set"
