#!/bin/sh

echo "-- Install setbg script --"


echo "-- Configure xserver --"
SCRIPTPATH=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
XSERVERPATH=$SCRIPTPATH/xserver-configs

cp $SCRIPTPATH/setbg ~/.config &

cp $XSERVERPATH/xinitrc ~/.xinitrc &
cp $XSERVERPATH/xprofile ~/.xprofile &
cp $XSERVERPATH/bash_profile ~/.bash_profile &
wait

echo "-- Configure xserver End --"
